<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>NAppUpdate.Framework</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net20</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Platform)' == 'ARM64'">
    <PlatformTarget>ARM64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Platform)' == 'ARM'">
    <PlatformTarget>ARM</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="NAppUpdate.Framework.updateicon.ico" />
    <EmbeddedResource Include="NAppUpdate.Framework.updateicon.ico" LogicalName="NAppUpdate.Framework.updateicon.ico" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Xml" />
  </ItemGroup>
</Project>
