namespace Substrate;

public enum HugeMushroomType
{
	FLESHY,
	CAP_CORNER_NORTHEAST,
	CAP_SIDE_EAST,
	CAP_CORNER_SOUTHEAST,
	CAP_SIDE_NORTH,
	CAP_TOP,
	CAP_SIDE_SOUTH,
	CAP_CORNER_NORTHWEST,
	CAP_SIDE_WEST,
	CAP_CORNER_SOUTHWEST,
	STEM
}
